/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.simercapp2.Vista;

import com.mycompany.simercapp2.Controlador.ControladorVistaAtarea;
import com.mycompany.simercapp2.Controlador.ControladorVistaEnCorreo;
import com.mycompany.simercapp2.Controlador.ControladorVistaLogin;
import com.mycompany.simercapp2.Controlador.ControladorVistaNcontacto;
import com.mycompany.simercapp2.Controlador.ControladorVistaNota;
import com.mycompany.simercapp2.Controlador.ControladorVistaPrincipal;
import com.mycompany.simercapp2.Controlador.ControladorVistaSeguimiento;
import com.mycompany.simercapp2.Controlador.ControladorVistaTareas;
import com.mycompany.simercapp2.Dao.RecordatorioDao;
import com.mycompany.simercapp2.Modelo.Nota;
import java.awt.Color;
import java.time.LocalDate;
import java.util.List;


import javax.swing.JOptionPane;

/**
 *
 * @author Ryzen
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    private int posL=0;
    public VistaPrincipal() {
        initComponents();
        txtDesc.setLineWrap(true);
        txtDesc.setWrapStyleWord(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnContact = new javax.swing.JPanel();
        btnNcontacto = new javax.swing.JLabel();
        pSeguimiento = new javax.swing.JPanel();
        btnSeguimiento = new javax.swing.JLabel();
        txtIdU = new javax.swing.JTextField();
        pEnCorreo = new javax.swing.JPanel();
        btnCorreo = new javax.swing.JLabel();
        pNota = new javax.swing.JPanel();
        btnNota = new javax.swing.JLabel();
        pAtarea = new javax.swing.JPanel();
        pTarea = new javax.swing.JPanel();
        btnTarea = new javax.swing.JLabel();
        btnAtarea = new javax.swing.JLabel();
        pMsj = new javax.swing.JPanel();
        msjTarea = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        btnA = new javax.swing.JLabel();
        btnS = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryzen\\simercApp2\\src\\main\\java\\com\\mycompany\\simercapp2\\Imagen\\salir.png")); // NOI18N
        jLabel3.setToolTipText("Cerrar Sesion");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 10, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryzen\\simercApp2\\src\\main\\java\\com\\mycompany\\simercapp2\\Imagen\\1668456118416.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 180));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BIENVENIDO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 654, 182));

        pnContact.setBackground(new java.awt.Color(153, 0, 0));

        btnNcontacto.setBackground(new java.awt.Color(153, 0, 0));
        btnNcontacto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnNcontacto.setForeground(new java.awt.Color(255, 255, 255));
        btnNcontacto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNcontacto.setText("NUEVO CONTACTO");
        btnNcontacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNcontacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNcontactoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNcontactoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNcontactoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnContactLayout = new javax.swing.GroupLayout(pnContact);
        pnContact.setLayout(pnContactLayout);
        pnContactLayout.setHorizontalGroup(
            pnContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNcontacto, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        pnContactLayout.setVerticalGroup(
            pnContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnContactLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pnContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        pSeguimiento.setBackground(new java.awt.Color(153, 0, 0));

        btnSeguimiento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnSeguimiento.setForeground(new java.awt.Color(255, 255, 255));
        btnSeguimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSeguimiento.setText("SEGUIMIENTO");
        btnSeguimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeguimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeguimientoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSeguimientoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeguimientoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pSeguimientoLayout = new javax.swing.GroupLayout(pSeguimiento);
        pSeguimiento.setLayout(pSeguimientoLayout);
        pSeguimientoLayout.setHorizontalGroup(
            pSeguimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSeguimientoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSeguimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pSeguimientoLayout.setVerticalGroup(
            pSeguimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSeguimientoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSeguimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pSeguimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, 43));

        txtIdU.setBackground(new java.awt.Color(255, 255, 255));
        txtIdU.setForeground(new java.awt.Color(255, 255, 255));
        txtIdU.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtIdU.setEnabled(false);
        txtIdU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pEnCorreo.setBackground(new java.awt.Color(153, 0, 0));

        btnCorreo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnCorreo.setForeground(new java.awt.Color(255, 255, 255));
        btnCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCorreo.setText("CORREO");
        btnCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCorreoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCorreoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCorreoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pEnCorreoLayout = new javax.swing.GroupLayout(pEnCorreo);
        pEnCorreo.setLayout(pEnCorreoLayout);
        pEnCorreoLayout.setHorizontalGroup(
            pEnCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEnCorreoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pEnCorreoLayout.setVerticalGroup(
            pEnCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEnCorreoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pEnCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        pNota.setBackground(new java.awt.Color(153, 0, 0));

        btnNota.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnNota.setForeground(new java.awt.Color(255, 255, 255));
        btnNota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNota.setText("NOTA");
        btnNota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNotaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pNotaLayout = new javax.swing.GroupLayout(pNota);
        pNota.setLayout(pNotaLayout);
        pNotaLayout.setHorizontalGroup(
            pNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNotaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNota, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pNotaLayout.setVerticalGroup(
            pNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNotaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNota, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, -1, 43));

        pAtarea.setBackground(new java.awt.Color(153, 0, 0));
        pAtarea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pTarea.setBackground(new java.awt.Color(153, 0, 0));
        pTarea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTarea.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnTarea.setForeground(new java.awt.Color(255, 255, 255));
        btnTarea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTarea.setText("TAREAS");
        btnTarea.setToolTipText("");
        btnTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTareaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTareaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTareaMouseExited(evt);
            }
        });
        pTarea.add(btnTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        pAtarea.add(pTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        btnAtarea.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnAtarea.setForeground(new java.awt.Color(255, 255, 255));
        btnAtarea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAtarea.setText("ASIG. TAREA");
        btnAtarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtareaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtareaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtareaMouseExited(evt);
            }
        });
        pAtarea.add(btnAtarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jPanel2.add(pAtarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 140, 40));

        pMsj.setBackground(new java.awt.Color(204, 204, 0));
        pMsj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        msjTarea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        msjTarea.setForeground(new java.awt.Color(0, 0, 0));
        msjTarea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pMsjLayout = new javax.swing.GroupLayout(pMsj);
        pMsj.setLayout(pMsjLayout);
        pMsjLayout.setHorizontalGroup(
            pMsjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(msjTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        pMsjLayout.setVerticalGroup(
            pMsjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMsjLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(msjTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pMsj, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 360, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1120, 600));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(204, 0, 0));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RECORDATORIO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 370, 50));

        txtTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 101, 370, 43));

        btnA.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryzen\\Documents\\NetBeansProjects\\SIMERC-pruebas\\SIMERC-pruebas\\src\\main\\java\\com\\mycompany\\simercapp2\\Imagen\\flechaAtras.png")); // NOI18N
        btnA.setToolTipText("Atras");
        btnA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAMouseClicked(evt);
            }
        });
        jPanel3.add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 30, 40));

        btnS.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryzen\\Documents\\NetBeansProjects\\SIMERC-pruebas\\SIMERC-pruebas\\src\\main\\java\\com\\mycompany\\simercapp2\\Imagen\\fechaSig.png")); // NOI18N
        btnS.setToolTipText("Siguiente");
        btnS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSMouseClicked(evt);
            }
        });
        jPanel3.add(btnS, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 30, 30));

        txtDesc.setBackground(new java.awt.Color(255, 255, 204));
        txtDesc.setColumns(20);
        txtDesc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtDesc.setForeground(new java.awt.Color(0, 0, 0));
        txtDesc.setRows(5);
        txtDesc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(txtDesc);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 340, 351));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 180, 380, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNcontactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNcontactoMouseClicked
        String idU=txtIdU.getText();
        
        
        ControladorVistaNcontacto ctrlNcontacto = new ControladorVistaNcontacto();
        ctrlNcontacto.mostrar(idU);
        this.dispose();
    }//GEN-LAST:event_btnNcontactoMouseClicked

    private void btnSeguimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeguimientoMouseClicked
        String idU=txtIdU.getText();
        ControladorVistaSeguimiento ctrlSeguimiento = new ControladorVistaSeguimiento();
        ctrlSeguimiento.iniciar(idU);
        this.dispose();
        
    }//GEN-LAST:event_btnSeguimientoMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int input = JOptionPane.showConfirmDialog(null, "SE VA A CERRAR LA SESION", "CERRAR SESION",
				JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        
        if(input == 0){
            ControladorVistaLogin ctrLogin= new ControladorVistaLogin();
            this.dispose();
            ctrLogin.iniciar();
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtIdUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUActionPerformed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        
    }//GEN-LAST:event_jLabel3MouseEntered

    private void btnCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCorreoMouseClicked
        String idU=txtIdU.getText();
        ControladorVistaEnCorreo ctrlEnCorreo = new ControladorVistaEnCorreo();
        ctrlEnCorreo.mostrar(idU);
        this.dispose();
    }//GEN-LAST:event_btnCorreoMouseClicked

    private void btnSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSMouseClicked
        posL+=1;
        int id= Integer.parseInt(txtIdU.getText());
        System.out.println(id);
        String titulo= "";
        String desc="";
        RecordatorioDao rDao= new RecordatorioDao();
        LocalDate fecha = LocalDate.now();
        String fech = String.valueOf(fecha);
        List<Nota> lista = rDao.recordatorio(id, fech);
        
        for(int i=0; i<lista.size();i++){
            titulo= lista.get(posL).getTitulo();
            desc= lista.get(posL).getDescripcion();
        }
        int num = lista.size();
        System.out.println(num);
        num-=1;
        txtTitulo.setText(titulo);
        txtDesc.setText(desc);
        
        btnA.setVisible(true);
        
        if(posL==num){
            btnS.setVisible(false);
        }else{
            btnS.setVisible(true);
        }
    }//GEN-LAST:event_btnSMouseClicked

    private void btnAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAMouseClicked
        posL-=1;
        int id= Integer.parseInt(txtIdU.getText());
        System.out.println(id);
        String titulo= "";
        String desc="";
        RecordatorioDao rDao= new RecordatorioDao();
        LocalDate fecha = LocalDate.now();
        String fech = String.valueOf(fecha);
        List<Nota> lista = rDao.recordatorio(id, fech);
        
        for(int i=0; i<lista.size();i++){
            titulo= lista.get(posL).getTitulo();
            desc= lista.get(posL).getDescripcion();
        }
        txtTitulo.setText(titulo);
        txtDesc.setText(desc);
        
        btnS.setVisible(true);
        
        if(posL==0){
            btnA.setVisible(false);
        }else{
            btnA.setVisible(true);
        }
    }//GEN-LAST:event_btnAMouseClicked

    private void btnNotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotaMouseClicked
        String id= txtIdU.getText();
        ControladorVistaNota ctrlvNota= new ControladorVistaNota();
        ctrlvNota.iniciar(id);
        this.dispose();
    }//GEN-LAST:event_btnNotaMouseClicked

    private void btnNcontactoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNcontactoMouseEntered
        pnContact.setBackground(Color.red);
        
    }//GEN-LAST:event_btnNcontactoMouseEntered

    private void btnSeguimientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeguimientoMouseEntered
        pSeguimiento.setBackground(Color.red);
    }//GEN-LAST:event_btnSeguimientoMouseEntered

    private void btnCorreoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCorreoMouseEntered
        pEnCorreo.setBackground(Color.red);
    }//GEN-LAST:event_btnCorreoMouseEntered

    private void btnNotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotaMouseEntered
        pNota.setBackground(Color.red);
    }//GEN-LAST:event_btnNotaMouseEntered

    private void btnAtareaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtareaMouseEntered
        pAtarea.setBackground(Color.red);
    }//GEN-LAST:event_btnAtareaMouseEntered

    private void btnNcontactoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNcontactoMouseExited
        pnContact.setBackground(new Color (153,0,0));
    }//GEN-LAST:event_btnNcontactoMouseExited

    private void btnSeguimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeguimientoMouseExited
        pSeguimiento.setBackground(new Color (153,0,0));
    }//GEN-LAST:event_btnSeguimientoMouseExited

    private void btnCorreoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCorreoMouseExited
        pEnCorreo.setBackground(new Color (153,0,0));
    }//GEN-LAST:event_btnCorreoMouseExited

    private void btnNotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotaMouseExited
        pNota.setBackground(new Color (153,0,0));
    }//GEN-LAST:event_btnNotaMouseExited

    private void btnAtareaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtareaMouseExited
        pAtarea.setBackground(new Color (153,0,0));
    }//GEN-LAST:event_btnAtareaMouseExited

    private void btnAtareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtareaMouseClicked
        String id = txtIdU.getText();
        ControladorVistaAtarea ctrAtarea = new ControladorVistaAtarea();
        ctrAtarea.iniciar(id);
        this.dispose();
    }//GEN-LAST:event_btnAtareaMouseClicked

    private void btnTareaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTareaMouseEntered
        pTarea.setBackground(Color.red);
    }//GEN-LAST:event_btnTareaMouseEntered

    private void btnTareaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTareaMouseExited
        pTarea.setBackground(new Color (153,0,0));
    }//GEN-LAST:event_btnTareaMouseExited

    private void btnTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTareaMouseClicked
        String id= txtIdU.getText();
        
        
        ControladorVistaTareas ctrTareas = new ControladorVistaTareas();
        ctrTareas.iniciar(id);
        this.dispose();
    }//GEN-LAST:event_btnTareaMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnA;
    public javax.swing.JLabel btnAtarea;
    private javax.swing.JLabel btnCorreo;
    public javax.swing.JLabel btnNcontacto;
    private javax.swing.JLabel btnNota;
    public javax.swing.JLabel btnS;
    public javax.swing.JLabel btnSeguimiento;
    public javax.swing.JLabel btnTarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel msjTarea;
    public javax.swing.JPanel pAtarea;
    private javax.swing.JPanel pEnCorreo;
    public javax.swing.JPanel pMsj;
    private javax.swing.JPanel pNota;
    private javax.swing.JPanel pSeguimiento;
    public javax.swing.JPanel pTarea;
    private javax.swing.JPanel pnContact;
    public javax.swing.JTextArea txtDesc;
    public javax.swing.JTextField txtIdU;
    public javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
