/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.simercapp2.Vista;

import com.mycompany.simercapp2.Controlador.ControladorVistaDetalle;
import com.mycompany.simercapp2.Controlador.ControladorVistaLogin;
import com.mycompany.simercapp2.Controlador.ControladorVistaPrincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryzen
 */
public class vistaSeguimiento extends javax.swing.JFrame {

    /**
     * Creates new form vistaSeguimiento
     */
    public vistaSeguimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jtBuscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tHistorial = new javax.swing.JTable();
        brnVer = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tContacto = new javax.swing.JTable();
        jtVer = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JLabel();
        txtidU = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 134));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 440, 110));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryzen\\simercApp2\\src\\main\\java\\com\\mycompany\\simercapp2\\Imagen\\salir.png")); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 10, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryzen\\simercApp2\\src\\main\\java\\com\\mycompany\\simercapp2\\Imagen\\1668456118416.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 140));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SEGUIMIENTO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 23, 347, 33));

        btnBuscar.setBackground(new java.awt.Color(204, 0, 0));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarKeyPressed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 20, -1, 30));

        jtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtBuscarKeyReleased(evt);
            }
        });
        jPanel2.add(jtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 281, -1));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("HISTORIAL COMUNICACION");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 350, -1, -1));

        tHistorial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tHistorial);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 746, 214));

        brnVer.setBackground(new java.awt.Color(204, 0, 0));
        brnVer.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        brnVer.setForeground(new java.awt.Color(255, 255, 255));
        brnVer.setText("VER");
        jPanel2.add(brnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        tContacto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tContactoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tContacto);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 82, 1439, 247));

        jtVer.setBackground(new java.awt.Color(255, 255, 255));
        jtVer.setForeground(new java.awt.Color(255, 255, 255));
        jtVer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtVer.setEnabled(false);
        jPanel2.add(jtVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 347, 50, -1));

        btnRegistrar.setBackground(new java.awt.Color(204, 0, 0));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 130, -1));

        btnVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryzen\\simercApp2\\src\\main\\java\\com\\mycompany\\simercapp2\\Imagen\\volver-flecha-izquierda_1.png")); // NOI18N
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        txtidU.setBackground(new java.awt.Color(255, 255, 255));
        txtidU.setForeground(new java.awt.Color(255, 255, 255));
        txtidU.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtidU.setEnabled(false);
        jPanel2.add(txtidU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1500, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBuscarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBuscarKeyReleased

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
       String id=txtidU.getText();
        ControladorVistaPrincipal ctrlVistaPrincipal = new ControladorVistaPrincipal();
       ctrlVistaPrincipal.iniciar(id);
       this.dispose();
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        String id=txtidU.getText();
        ControladorVistaPrincipal ctrlPrincipal = new ControladorVistaPrincipal();
        ctrlPrincipal.iniciar(id);
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        int input = JOptionPane.showConfirmDialog(null, "SE VA A CERRAR LA SESION", "CERRAR SESION",
				JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        
        
        if(input == 0){
            ControladorVistaLogin ctrLogin= new ControladorVistaLogin();
            this.dispose();
            ctrLogin.iniciar();
        }
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarKeyPressed
        
        
    }//GEN-LAST:event_btnBuscarKeyPressed

    private void tContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tContactoMouseClicked
        int fila=tContacto.getSelectedRow();
        System.out.println(fila);
        ;
        if(fila>=0){
            String id=(String)tContacto.getValueAt(fila,0).toString();
            jtVer.setText(id);
            System.out.println(id);
        }
        
        
        
        ControladorVistaDetalle ctrVistaDetalle= new ControladorVistaDetalle();
        ctrVistaDetalle.mostrar(jtVer.getText());
        this.dispose();
    }//GEN-LAST:event_tContactoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaSeguimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton brnVer;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JLabel btnInicio;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JLabel btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextField jtBuscar;
    public javax.swing.JTextField jtVer;
    public javax.swing.JTable tContacto;
    public javax.swing.JTable tHistorial;
    public javax.swing.JTextField txtidU;
    // End of variables declaration//GEN-END:variables
}
