/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.simercapp2.Vista;

import com.mycompany.simercapp2.Controlador.ControladorVistaLogin;
import com.mycompany.simercapp2.Controlador.ControladorVistaPrincipal;
import com.mycompany.simercapp2.Dao.AtareaDao;
import com.mycompany.simercapp2.Modelo.AsignarTarea;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryzen
 */
public class VistaTarea extends javax.swing.JFrame {

    /**
     * Creates new form VistaTarea
     */
    int posL=0;
    public VistaTarea() {
        initComponents();
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdU = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnRealizada = new javax.swing.JButton();
        siguiente = new javax.swing.JLabel();
        atras = new javax.swing.JLabel();
        txtIdTarea = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 430, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryzen\\Documents\\NetBeansProjects\\SIMERC-pruebas\\SIMERC-pruebas\\src\\main\\java\\com\\mycompany\\simercapp2\\Imagen\\salir.png")); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 10, -1, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TAREAS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 6, 396, 36));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryzen\\Documents\\NetBeansProjects\\SIMERC-pruebas\\SIMERC-pruebas\\src\\main\\java\\com\\mycompany\\simercapp2\\Imagen\\volver-flecha-izquierda_1.png")); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        txtIdU.setBackground(new java.awt.Color(255, 255, 255));
        txtIdU.setForeground(new java.awt.Color(255, 255, 255));
        txtIdU.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtIdU.setEnabled(false);
        jPanel2.add(txtIdU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));

        txtTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 50));

        txtDescripcion.setBackground(new java.awt.Color(255, 255, 204));
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 430, 310));

        btnRealizada.setBackground(new java.awt.Color(0, 204, 0));
        btnRealizada.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnRealizada.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizada.setText("REALIZADA");
        jPanel3.add(btnRealizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 490, 500));

        siguiente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryzen\\Documents\\NetBeansProjects\\SIMERC-pruebas\\SIMERC-pruebas\\src\\main\\java\\com\\mycompany\\simercapp2\\Imagen\\fechaSig.png")); // NOI18N
        siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siguienteMouseClicked(evt);
            }
        });
        jPanel2.add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 290, -1, -1));

        atras.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryzen\\Documents\\NetBeansProjects\\SIMERC-pruebas\\SIMERC-pruebas\\src\\main\\java\\com\\mycompany\\simercapp2\\Imagen\\flechaAtras.png")); // NOI18N
        atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
        });
        jPanel2.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        txtIdTarea.setBackground(new java.awt.Color(255, 255, 255));
        txtIdTarea.setForeground(new java.awt.Color(255, 255, 255));
        txtIdTarea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtIdTarea.setEnabled(false);
        jPanel2.add(txtIdTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1500, 630));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryzen\\Documents\\NetBeansProjects\\SIMERC-pruebas\\SIMERC-pruebas\\src\\main\\java\\com\\mycompany\\simercapp2\\Imagen\\salir.png")); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 10, -1, 40));

        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 430, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryzen\\Documents\\NetBeansProjects\\SIMERC-pruebas\\SIMERC-pruebas\\src\\main\\java\\com\\mycompany\\simercapp2\\Imagen\\1668456118416.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 135));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        String idU = txtIdU.getText();

        ControladorVistaPrincipal ctrlvPrincipal= new ControladorVistaPrincipal();
        ctrlvPrincipal.iniciar(idU);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        int input = JOptionPane.showConfirmDialog(null, "SE VA A CERRAR LA SESION", "CERRAR SESION",
            JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

        if(input == 0){
            ControladorVistaLogin ctrLogin= new ControladorVistaLogin();
            this.dispose();
            ctrLogin.iniciar();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        String idU = txtIdU.getText();

        ControladorVistaPrincipal ctrlvPrincipal= new ControladorVistaPrincipal();
        ctrlvPrincipal.iniciar(idU);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        int input = JOptionPane.showConfirmDialog(null, "SE VA A CERRAR LA SESION", "CERRAR SESION",
            JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

        if(input == 0){
            ControladorVistaLogin ctrLogin= new ControladorVistaLogin();
            this.dispose();
            ctrLogin.iniciar();
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        String idU = txtIdU.getText();

        ControladorVistaPrincipal ctrlvPrincipal= new ControladorVistaPrincipal();
        ctrlvPrincipal.iniciar(idU);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguienteMouseClicked
        posL+=1;
        int id= Integer.parseInt(txtIdU.getText());
        AtareaDao atareaDao = new AtareaDao();
        
        LocalDate fecha= LocalDate.now();
        String fech = String.valueOf(fecha);
        String titulo="";
        String desc= "";
        int idF=0;
        
        List<AsignarTarea> lista= atareaDao.mostrarTarea(id, fech);
        
        for(int i=0;i<lista.size();i++){
            
            idF= lista.get(posL).getId();
            titulo= lista.get(posL).getTitulo();
            desc= lista.get(posL).getDescripcion();
            
        }
        String idTarea= String.valueOf(idF);
        
        txtIdTarea.setText(idTarea);
        txtTitulo.setText(titulo);
        txtDescripcion.setText(desc);
        int num= lista.size();
        num-=1;
        if(posL==num){
            siguiente.setVisible(false);
        }else{
            siguiente.setVisible(true);
        }
        atras.setVisible(true);
    }//GEN-LAST:event_siguienteMouseClicked

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        posL-=1;
        int id= Integer.parseInt(txtIdU.getText());
        AtareaDao atareaDao = new AtareaDao();
        
        LocalDate fecha= LocalDate.now();
        String fech = String.valueOf(fecha);
        String titulo="";
        String desc= "";
        int idF=0;
        
        List<AsignarTarea> lista= atareaDao.mostrarTarea(id, fech);
        
        for(int i=0;i<lista.size();i++){
            
            idF= lista.get(posL).getId();
            titulo= lista.get(posL).getTitulo();
            desc= lista.get(posL).getDescripcion();
            
        }
        String idTarea= String.valueOf(idF);
        
        txtIdTarea.setText(idTarea);
        txtTitulo.setText(titulo);
        txtDescripcion.setText(desc);
        int num= lista.size();
        if(posL==0){
            atras.setVisible(false);
        }else{
            atras.setVisible(true);
        }
        siguiente.setVisible(true);
    }//GEN-LAST:event_atrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel atras;
    public javax.swing.JButton btnRealizada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel siguiente;
    public javax.swing.JTextArea txtDescripcion;
    public javax.swing.JTextField txtIdTarea;
    public javax.swing.JTextField txtIdU;
    public javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
