/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.simercapp2.Vista;

import java.awt.Color;

/**
 *
 * @author Ryzen
 */
public class vistaLogin extends javax.swing.JFrame {

    /**
     * Creates new form vistaLogin
     */
    public vistaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaRegistrar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtDocumento = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jtCorreo = new javax.swing.JTextField();
        jtContraseña = new javax.swing.JTextField();
        pGuardar = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JLabel();
        pCancelar = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtConCorreo = new javax.swing.JTextField();
        pValAdmin = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pAceptar = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JLabel();
        pCancel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JLabel();
        txtClaveAd = new javax.swing.JPasswordField();
        txtConInVal = new javax.swing.JLabel();
        ventanaInicioSesion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jtUser = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        pIngresar = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JLabel();
        pRegistrar = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtPass = new javax.swing.JPasswordField();
        pSalir = new javax.swing.JPanel();
        btnSalir = new javax.swing.JLabel();
        txtConIn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ventanaRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        ventanaRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRAR");
        ventanaRegistrar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 52, 294, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Documento:");
        ventanaRegistrar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 144, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nombre:");
        ventanaRegistrar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 194, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Apellido:");
        ventanaRegistrar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 247, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Correo:");
        ventanaRegistrar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 298, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Contraseña:");
        ventanaRegistrar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 348, -1, -1));
        ventanaRegistrar.add(jtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 270, -1));
        ventanaRegistrar.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 270, -1));

        jtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtApellidoActionPerformed(evt);
            }
        });
        ventanaRegistrar.add(jtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 270, -1));
        ventanaRegistrar.add(jtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 270, -1));
        ventanaRegistrar.add(jtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 270, -1));

        pGuardar.setBackground(new java.awt.Color(0, 204, 0));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("REGISTRAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pGuardarLayout = new javax.swing.GroupLayout(pGuardar);
        pGuardar.setLayout(pGuardarLayout);
        pGuardarLayout.setHorizontalGroup(
            pGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pGuardarLayout.setVerticalGroup(
            pGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        ventanaRegistrar.add(pGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 130, -1));

        pCancelar.setBackground(new java.awt.Color(204, 0, 0));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("CANCELAR");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pCancelarLayout = new javax.swing.GroupLayout(pCancelar);
        pCancelar.setLayout(pCancelarLayout);
        pCancelarLayout.setHorizontalGroup(
            pCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );
        pCancelarLayout.setVerticalGroup(
            pCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        ventanaRegistrar.add(pCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Contraseñ del correo:");
        ventanaRegistrar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 220, -1));
        ventanaRegistrar.add(jtConCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 270, -1));

        getContentPane().add(ventanaRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 650));

        pValAdmin.setBackground(new java.awt.Color(255, 255, 255));
        pValAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pValAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("INGRESE CLAVE DE ADMINISTRADOR");
        pValAdmin.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 520, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryzen\\simercApp2\\src\\main\\java\\com\\mycompany\\simercapp2\\Imagen\\candado.png")); // NOI18N
        pValAdmin.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 161, -1, -1));

        pAceptar.setBackground(new java.awt.Color(153, 0, 0));

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAceptar.setText("ACEPTAR");
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceptarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pAceptarLayout = new javax.swing.GroupLayout(pAceptar);
        pAceptar.setLayout(pAceptarLayout);
        pAceptarLayout.setHorizontalGroup(
            pAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAceptarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pAceptarLayout.setVerticalGroup(
            pAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAceptarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pValAdmin.add(pAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        pCancel.setBackground(new java.awt.Color(255, 255, 255));

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 0, 0));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setText("X");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pCancelLayout = new javax.swing.GroupLayout(pCancel);
        pCancel.setLayout(pCancelLayout);
        pCancelLayout.setHorizontalGroup(
            pCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCancelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pCancelLayout.setVerticalGroup(
            pCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pValAdmin.add(pCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 50));
        pValAdmin.add(txtClaveAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 340, -1));

        txtConInVal.setForeground(new java.awt.Color(204, 0, 0));
        txtConInVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtConInVal.setText("CONTRASEÑA INCORRECTA");
        pValAdmin.add(txtConInVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 340, -1));

        getContentPane().add(pValAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 520, 340));

        ventanaInicioSesion.setBackground(new java.awt.Color(255, 255, 255));
        ventanaInicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 0, 0));
        ventanaInicioSesion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 440, 650));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CONTRASEÑA:");
        ventanaInicioSesion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 150, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        ventanaInicioSesion.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 430, 10));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("USUARIO:");
        ventanaInicioSesion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, -1));

        jtUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtUser.setForeground(new java.awt.Color(0, 0, 0));
        jtUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtUserMousePressed(evt);
            }
        });
        ventanaInicioSesion.add(jtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 430, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        ventanaInicioSesion.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 430, 10));

        pIngresar.setBackground(new java.awt.Color(153, 0, 0));

        btnIngresar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIngresar.setText("INGRESAR");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pIngresarLayout = new javax.swing.GroupLayout(pIngresar);
        pIngresar.setLayout(pIngresarLayout);
        pIngresarLayout.setHorizontalGroup(
            pIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pIngresarLayout.setVerticalGroup(
            pIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        ventanaInicioSesion.add(pIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 130, 50));

        pRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        pRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnRegistrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pRegistrarLayout = new javax.swing.GroupLayout(pRegistrar);
        pRegistrar.setLayout(pRegistrarLayout);
        pRegistrarLayout.setHorizontalGroup(
            pRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pRegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pRegistrarLayout.setVerticalGroup(
            pRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pRegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ventanaInicioSesion.add(pRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 130, 50));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INICIO DE SESION");
        ventanaInicioSesion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 610, -1));

        jtPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtPass.setForeground(new java.awt.Color(0, 0, 0));
        jtPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtPassMousePressed(evt);
            }
        });
        ventanaInicioSesion.add(jtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 430, 20));

        pSalir.setBackground(new java.awt.Color(255, 255, 255));
        pSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pSalirMouseExited(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.setText("X");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pSalirLayout = new javax.swing.GroupLayout(pSalir);
        pSalir.setLayout(pSalirLayout);
        pSalirLayout.setHorizontalGroup(
            pSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pSalirLayout.setVerticalGroup(
            pSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSalirLayout.createSequentialGroup()
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(605, 605, 605))
        );

        ventanaInicioSesion.add(pSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        txtConIn.setForeground(new java.awt.Color(204, 0, 0));
        txtConIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtConIn.setText("USUARIO O CONTRASEÑA INCORRECTA");
        ventanaInicioSesion.add(txtConIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 430, 30));

        getContentPane().add(ventanaInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        pSalir.setBackground(Color.red);
        btnSalir.setForeground(Color.white);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void pSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSalirMouseEntered

    }//GEN-LAST:event_pSalirMouseEntered

    private void pSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSalirMouseExited

    }//GEN-LAST:event_pSalirMouseExited

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
         pSalir.setBackground(Color.white);
        btnSalir.setForeground(Color.black);
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked

    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered
        pRegistrar.setBackground(new Color(153, 0, 0));
        btnRegistrar.setForeground(Color.white);
    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        pRegistrar.setBackground(Color.white);
        btnRegistrar.setForeground(Color.black);
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
        pIngresar.setBackground(Color.red);
    }//GEN-LAST:event_btnIngresarMouseEntered

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
        pIngresar.setBackground(new Color(153, 0, 0));
    }//GEN-LAST:event_btnIngresarMouseExited

    private void jtUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUserMousePressed
        

    }//GEN-LAST:event_jtUserMousePressed

    private void jtPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPassMousePressed
        
    }//GEN-LAST:event_jtPassMousePressed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void jtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtApellidoActionPerformed

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        pCancelar.setBackground(new Color (153,0,0));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        pCancelar.setBackground(new Color (204,0,0));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        pGuardar.setBackground(new Color (0,153,0));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        pGuardar.setBackground(new Color (0,204,0));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        pValAdmin.setVisible(false);
        ventanaInicioSesion.setVisible(true);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        pCancel.setBackground(Color.red);
        btnCancel.setForeground(Color.white);
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        pCancel.setBackground(Color.white);
        btnCancel.setForeground(Color.black);
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseEntered
        pAceptar.setBackground(Color.red);
    }//GEN-LAST:event_btnAceptarMouseEntered

    private void btnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseExited
        pAceptar.setBackground(new Color (153,0,0));
    }//GEN-LAST:event_btnAceptarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnAceptar;
    private javax.swing.JLabel btnCancel;
    public javax.swing.JLabel btnCancelar;
    public javax.swing.JLabel btnGuardar;
    public javax.swing.JLabel btnIngresar;
    public javax.swing.JLabel btnRegistrar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField jtApellido;
    public javax.swing.JTextField jtConCorreo;
    public javax.swing.JTextField jtContraseña;
    public javax.swing.JTextField jtCorreo;
    public javax.swing.JTextField jtDocumento;
    public javax.swing.JTextField jtNombre;
    public javax.swing.JPasswordField jtPass;
    public javax.swing.JTextField jtUser;
    private javax.swing.JPanel pAceptar;
    private javax.swing.JPanel pCancel;
    private javax.swing.JPanel pCancelar;
    private javax.swing.JPanel pGuardar;
    private javax.swing.JPanel pIngresar;
    private javax.swing.JPanel pRegistrar;
    private javax.swing.JPanel pSalir;
    public javax.swing.JPanel pValAdmin;
    public javax.swing.JPasswordField txtClaveAd;
    public javax.swing.JLabel txtConIn;
    public javax.swing.JLabel txtConInVal;
    public javax.swing.JPanel ventanaInicioSesion;
    public javax.swing.JPanel ventanaRegistrar;
    // End of variables declaration//GEN-END:variables

}
